package com.techno.mpm.enumeration;

public enum CandidateEnum {

	
	AVAILABLE, NOT_AVAILABLE, SELECTED, DEPLOYED, SOURCED, INTERVIEW_SCHEDULED, INTERVIEW_REJECT, BLOCKED_BY_TY,
	SELECTED_FOR_OTHER_COMPANY, NOT_INTERESTED_FOR_TY, OFFER_DECLINED, CLIENT_SELECT, EDF_SENT, OFFER_RELEASED,
	YET_TO_JOIN_TY, ONBOARDED_TO_TY, ALL,REJECTED, RESCHEDULE, SCHEDULE, ON_HOLD, HOLD
}
